src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SessionRepository::class)]
class Session
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $intitule = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $DateDebut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateFin = null;

    #[ORM\Column]
    private ?int $nbPlacesTotales = null;

    #[ORM\ManyToOne(inversedBy: 'sessions')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Formateur $formateur = null;

    /**
     * @var Collection<int, Inscrire>
     */
    #[ORM\OneToMany(targetEntity: Inscrire::class, mappedBy: 'session', orphanRemoval: true)]
    private Collection $inscriptions;

    /**
     * @var Collection<int, Programme>
     */
    #[ORM\OneToMany(targetEntity: Programme::class, mappedBy: 'session', orphanRemoval: true)]
    private Collection $programmes;

    public function __construct()
    {
        $this->inscriptions = new ArrayCollection();
        $this->programmes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIntitule(): ?string
    {
        return $this->intitule;
    }

    public function setIntitule(string $intitule): static
    {
        $this->intitule = $intitule;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->DateDebut;
    }

    public function setDateDebut(\DateTimeInterface $DateDebut): static
    {
        $this->DateDebut = $DateDebut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->dateFin;
    }

    public function setDateFin(\DateTimeInterface $dateFin): static
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    public function getNbPlacesTotales(): ?int
    {
        return $this->nbPlacesTotales;
    }

    public function setNbPlacesTotales(int $nbPlacesTotales): static
    {
        $this->nbPlacesTotales = $nbPlacesTotales;

        return $this;
    }

    public function getFormateur(): ?Formateur
    {
        return $this->formateur;
    }

    public function setFormateur(?Formateur $formateur): static
    {
        $this->formateur = $formateur;

        return $this;
    }

    /**
     * @return Collection<int, Inscrire>
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscrire $inscription): static
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions->add($inscription);
            $inscription->setSession($this);
        }

        return $this;
    }

    public function removeInscription(Inscrire $inscription): static
    {
        if ($this->inscriptions->removeElement($inscription)) {
            // set the owning side to null (unless already changed)
            if ($inscription->getSession() === $this) {
                $inscription->setSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Programme>
     */
    public function getProgrammes(): Collection
    {
        return $this->programmes;
    }

    public function addProgramme(Programme $programme): static
    {
        if (!$this->programmes->contains($programme)) {
            $this->programmes->add($programme);
            $programme->setSession($this);
        }

        return $this;
    }

    public function removeProgramme(Programme $programme): static
    {
        if ($this->programmes->removeElement($programme)) {
            // set the owning side to null (unless already changed)
            if ($programme->getSession() === $this) {
                $programme->setSession(null);
            }
        }

        return $this;
    }
}

src/Entity/Stagiaire.php
<?php

namespace App\Entity;

use App\Repository\StagiaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StagiaireRepository::class)]
class Stagiaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\Column]
    private ?bool $sexe = null;

    #[ORM\Column(length: 100)]
    private ?string $email = null;

    #[ORM\Column(length: 30)]
    private ?string $ville = null;

    #[ORM\Column(length: 30)]
    private ?string $telephone = null;

    /**
     * @var Collection<int, Inscrire>
     */
    #[ORM\OneToMany(targetEntity: Inscrire::class, mappedBy: 'stagiaire', orphanRemoval: true)]
    private Collection $inscriptions;

    public function __construct()
    {
        $this->inscriptions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(\DateTimeInterface $dateNaissance): static
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function isSexe(): ?bool
    {
        return $this->sexe;
    }

    public function setSexe(bool $sexe): static
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    /**
     * @return Collection<int, Inscrire>
     */
    public function getInscriptions(): Collection
    {
        return $this->inscriptions;
    }

    public function addInscription(Inscrire $inscription): static
    {
        if (!$this->inscriptions->contains($inscription)) {
            $this->inscriptions->add($inscription);
            $inscription->setStagiaire($this);
        }

        return $this;
    }

    public function removeInscription(Inscrire $inscription): static
    {
        if ($this->inscriptions->removeElement($inscription)) {
            // set the owning side to null (unless already changed)
            if ($inscription->getStagiaire() === $this) {
                $inscription->setStagiaire(null);
            }
        }

        return $this;
    }
}

src/Form/StagiaireType.php
<?php

namespace App\Form;

use App\Entity\Stagiaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class StagiaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class)
            ->add('prenom', TextType::class)
            ->add('dateNaissance', DateType::class, [
                'widget' => 'single_text',
                'attr' => ['class' => 'datepicker'],
                'label' => 'Date de naissance',
                'required' => true,
            ])
            ->add('sexe', ChoiceType::class, [
                'choices' => [
                    'M' => true,
                    'F' => false,
                ],
                'expanded' => true,
                'multiple' => false,
                'required' => true,
                'label' => 'Sexe',
            ])
            ->add('email', EmailType::class)
            ->add('ville', TextType::class)
            ->add('telephone', TextType::class)
            ->add('save', SubmitType::class, [
                'label' => 'Créer Stagiaire',
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Stagiaire::class,
        ]);
    }
}

src/Controller/StagiaireController.php
<?php

namespace App\Controller;

use App\Entity\Stagiaire;
use App\Form\StagiaireType;
use App\Repository\StagiaireRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class StagiaireController extends AbstractController
{
    #[Route('/stagiaire', name: 'app_stagiaire')]
    public function index(): Response
    {
        return $this->render('stagiaire/index.html.twig', [
            'controller_name' => 'StagiaireController',
        ]);
    }

    #[Route('/stagiaires', name: 'stagiaires_list')]
    public function list(StagiaireRepository $stagiaireRepository, Request $request, EntityManagerInterface $entityManager): Response
    {
        $stagiaires = $stagiaireRepository->findAll();
        $stagiaire = new Stagiaire();
        $form = $this->createForm(StagiaireType::class, $stagiaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($stagiaire);
            $entityManager->flush();

            $this->addFlash('success', 'Le stagiaire a bien été inscrit');

            return $this->redirectToRoute('stagiaires_list');
        }

        return $this->render('stagiaire/list.html.twig', [
            'stagiaires' => $stagiaires,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/stagiaire/{id}', name: 'stagiaire_detail')]
    public function detail(StagiaireRepository $stagiaireRepository, int $id): Response
    {
        $stagiaire = $stagiaireRepository->find($id);

        if (!$stagiaire) {
            throw $this->createNotFoundException("Le stagiaire n'existe pas");
        }

        // Calcul des places restantes pour chaque session
        $sessionsWithRemainingPlaces = [];
        foreach ($stagiaire->getInscriptions() as $inscription) {
            $session = $inscription->getSession();
            $placesRestantes = $session->getNbPlacesTotales() - count($session->getInscriptions());
            $sessionsWithRemainingPlaces[] = [
                'session' => $session,
                'placesRestantes' => $placesRestantes
            ];
        }

        return $this->render('stagiaire/detail.html.twig', [
            'stagiaire' => $stagiaire,
            'sessionsWithRemainingPlaces' => $sessionsWithRemainingPlaces,
        ]);
    }
    #[Route('/stagiaire/delete/{id}', name: 'stagiaire_delete', methods: ['POST'])]
    public function delete(Request $request, EntityManagerInterface $entityManager, Stagiaire $stagiaire): Response
    {
        if ($this->isCsrfTokenValid('delete' . $stagiaire->getId(), $request->request->get('_token'))) {
            $entityManager->remove($stagiaire);
            $entityManager->flush();
            $this->addFlash('success', 'Le stagiaire a été supprimé avec succès');
        } else {
            $this->addFlash('error', 'Token CSRF invalide');
        }

        return $this->redirectToRoute('stagiaires_list');
    }
}

templates/stagiaire/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail du Stagiaire
{% endblock %}

{% block body %}
	<div class="wrapper">
		<div class="session-list-container wrapper-col">
			<h4>Détail du Stagiaire</h4>
			<p>Nom :
				{{ stagiaire.nom }}</p>
			<p>Prénom :
				{{ stagiaire.prenom }}</p>
			<p>Date de naissance :
				{{ stagiaire.dateNaissance|date('d-m-Y') }}</p>
			<p>Sexe :
				{{ stagiaire.sexe == 1 ? 'Masculin' : 'Féminin' }}</p>
			<p>Email :
				{{ stagiaire.email }}</p>
			<p>Ville :
				{{ stagiaire.ville }}</p>
			<p>Téléphone :
				{{ stagiaire.telephone }}</p>
		</div>

		<div class="session-list-container wrapper-col">
			<h4>Sessions inscrites</h4>
			<ul>
				{% for sessionWithPlaces in sessionsWithRemainingPlaces %}
					{% set session = sessionWithPlaces.session %}
					{% set placesRestantes = sessionWithPlaces.placesRestantes %}
					<li>
						<a href="{{ path('session_detail', {'id': session.id}) }}">
							{{ session.intitule }}
							:
							<br>
							Du
							{{ session.dateDebut|date('d-m-Y') }}
							au
							{{ session.dateFin|date('d-m-Y') }}
							|
							{{ session.formateur.nom }}
							{{ session.formateur.prenom }}
							|
														 ({{ placesRestantes }}
							places restantes)
						</a>
					</li>
				{% endfor %}
			</ul>
		</div>
	</div>
{% endblock %}

templates/stagiaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StagiaireController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/Users/luigi/Desktop/Formation/Elan/Sources/Symfony/Sessions/src/Controller/StagiaireController.php</code></li>
        <li>Your template at <code>C:/Users/luigi/Desktop/Formation/Elan/Sources/Symfony/Sessions/templates/stagiaire/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/stagiaire/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Stagiaires
{% endblock %}

{% block body %}
	<div class="wrapper">
		<div class="session-list-container wrapper-col">
			<h4>Liste des Stagiaires</h4>
			<ul>
				{% for stagiaire in stagiaires %}
					<li class="delete-item">
						<a href="{{ path('stagiaire_detail', { 'id': stagiaire.id }) }}">
							{{ stagiaire.nom }}
							{{ stagiaire.prenom }}
						</a>
						<form method="post" action="{{ path('stagiaire_delete', {'id': stagiaire.id}) }}" style="display:inline;" class="delete-form">
							<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ stagiaire.id) }}">
							<button class="btn btn-danger btn-sm" type="submit">-</button>
						</form>
					</li>
				{% endfor %}
			</ul>
		</div>
		<div class="session-list-container wrapper-col">
			<h4>Ajouter un Stagiaire</h4>
			<div class="stagiaire-form-container">
				{{ form_start(form) }}
				{{ form_widget(form) }}
				{{ form_end(form) }}
			</div>
		</div>
	</div>
{% endblock %}